name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-18.04
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.1.5"

      - name: Setup Luarocks
        uses: leafo/gh-actions-luarocks@v4
        with:
          luarocksVersion: "3.8.0"

      - name: Linux Get dependencies
        run: sudo apt install -y build-essential libncurses5-dev libreadline-dev libssl-dev perl

      - name: Linux Install
        run: |
          wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
          sudo apt-get -y install software-properties-common
          sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
          sudo apt-get update
          sudo apt-get install openresty

      - name: Linux Script
        run: |
          luarocks make rockspec/jsonschema-master-0.rockspec
          export PATH=$OPENRESTY_PREFIX/nginx/sbin:$PATH
          make test
